a_feat_dim: 768
a_feat_dir: dataset/clotho-moment/clap
a_feat_type: clap
a_sub_feat_dir: private/feature/clap
aux_loss: true
bsz: 1
ckpt_filename: best_checkpoint.pth
clip_length: 1
ctx_mode: audio_tef
dec_layers: 2
device: cpu
dim_feedforward: 1024
dropout: 0.1
dset_name: clotho-moment
ema_decay: 0.9
enc_layers: 2
eos_coef: 0.1
eval_bsz: 1
eval_epoch_interval: 1
eval_log_filename: val.log
eval_split_name: val
giou_loss_coef: 1
grad_clip: 0.1
hidden_dim: 256
input_dropout: 0.5
label_loss_coef: 4
lr: 0.0001
lr_drop: 400
lw_saliency: 1
max_a_l: 300
max_q_l: 32
max_windows: 5
model_ema: false
model_name: lcs_detr
n_epoch: 1
n_input_proj: 2
nheads: 8
num_queries: 10
num_workers: 4
position_embedding: learned
results_dir: results_test_learned
saliency_margin: 0.2
seed: 2023
set_cost_class: 4
set_cost_giou: 1
set_cost_span: 10
span_loss_coef: 10
span_loss_type: l1
submission_path: private/dcase2026_private.jsonl
t_feat_dim: 768
t_feat_dir: dataset/clotho-moment/clap_text
t_feat_type: clap
t_sub_feat_dir: private/feature/clap_text
test_path: dataset/preprocessed/clotho_moment_valid_test.jsonl
train_log_filename: train.log
train_path: dataset/preprocessed/clotho_moment_valid_train.jsonl
val_path: dataset/preprocessed/clotho_moment_valid_val.jsonl
wd: 0.0001
